### ISSUE TITLE
Use Natural Language for Commands

### ISSUE THREAD

**Issue by mutewinter** [postlight/hubot-spotify-playlist#1]
Since these commands are typed by non-programmers, English words are common for Hubot plugins.

- `findTrack` could become `spotify find <query>`
- `addTrack` could become `spotify queue <query>`
- `getToken` could become `spotify get token`
- `removeTrack` could become `spotify (unqueue|remove) <query>`

**Comment by kev5873** [comment]
This sounds like a good idea, there's still the limitation of requiring the user to use their own access token though.  So maybe something like this instead.

- `findTrack` could become `spotify find <query>`
- `addTrack` could become `spotify queue <query> <key>`
- `getToken` could become `spotify get token`
- `removeTrack` could become `spotify (unqueue|remove) <query> <key>`

**Comment by mutewinter** [comment]
Oh interesting, I didn't realize that limitation existed. It sounds like something that should be rolled into the bot. The bot itself has a [Redis-based brain](https://hubot.github.com/docs/scripting/#persistence) that can store data between requests. Perhaps we could authenticate and have it re-authenticate behind the scenes as necessary? Or at least save the last key.
