### ISSUE TITLE
Preserve Spotify Key so Users Don't Have to Send It

### ISSUE THREAD

**Issue by mutewinter** [postlight/hubot-spotify-playlist#2]
From #1.

> Oh interesting, I didn't realize that limitation existed. It sounds like something that should be rolled into the bot. The bot itself has a Redis-based brain that can store data between requests. Perhaps we could authenticate and have it re-authenticate behind the scenes as necessary? Or at least save the last key.

**Comment by kev5873** [comment]
Right this would need to be a user based operation, as they have to authorize a set of permissions so we can add items to the playlist on their behalf.

What I might be able to do is to have the Postlight account ask for an OAuth token, and reuse the same token continuously with the refresh token to refresh when needed.  That way I can have full access to the API as if it were a user.
